server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/user-service-fallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/department-service-fallback
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeOutInMilliSeconds: 4000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health
    hystrix:
      stream:
        enabled: true


#eureka:
  #client:
    #register-with-eureka: true
    #fetch-registry: true
    #service-url:
      #default-zone: http://localhost:8761/eureka
  #instance:
   # hostname: localhost
